import { Unit } from "@/types/unit";

export const MOCK_PROPERTIES: Unit[] = [
    {
        id: "1",
        title: "Grand House Real Estate",
        location: "New Cairo, Egypt",
        price: 13500000,
        rooms: 3,
        bathrooms: 3,
        area: 250,
        image: "/unit_1.png",
        status: "approved",
        addedDate: "31/8/2022",
    },
    {
        id: "2",
        title: "Grand House Real Estate",
        location: "New Cairo, Egypt",
        price: 15500000,
        rooms: 3,
        bathrooms: 3,
        area: 250,
        image: "/unit_2.png",
        status: "pending",
        addedDate: "29/8/2022",
    },
    {
        id: "3",
        title: "Grand House Real Estate",
        location: "New Cairo, Egypt",
        price: 11500000,
        rooms: 3,
        bathrooms: 3,
        area: 250,
        image: "/unit_3.png",
        status: "approved",
        reserved: true,
        addedDate: "1/9/2022",
        assignedTo: "Mohamed Sami",
    },
    {
        id: "4",
        title: "Grand House Real Estate",
        location: "New Cairo, Egypt",
        price: 17500000,
        rooms: 3,
        bathrooms: 3,
        area: 250,
        image: "/unit_4.png",
        status: "rejected",
        addedDate: "10/9/2022",
    },
    {
        id: "1231",
        title: "Grand House Real Estate",
        location: "New Cairo, Egypt",
        price: 19500000,
        rooms: 3,
        bathrooms: 3,
        area: 250,
        image: "/unit_1.png",
        status: "approved",
        addedDate: "31/7/2022",
    },
    {
        id: "1232",
        title: "Grand House Real Estate",
        location: "New Cairo, Egypt",
        price: 10500000,
        rooms: 3,
        bathrooms: 3,
        area: 250,
        image: "/unit_2.png",
        status: "pending",
        addedDate: "5/7/2020",
    },
    {
        id: "1233",
        title: "Grand House Real Estate",
        location: "New Cairo, Egypt",
        price: 7500000,
        rooms: 3,
        bathrooms: 3,
        area: 250,
        image: "/unit_3.png",
        status: "approved",
        reserved: true,
        addedDate: "15/8/2022",
        assignedTo: "Mohamed Sami",
    },
    {
        id: "121233",
        title: "Grand House Real Estate",
        location: "New Cairo, Egypt",
        price: 7500000,
        rooms: 3,
        bathrooms: 3,
        area: 250,
        image: "/unit_3.png",
        status: "rejected",
        addedDate: "15/8/2022",
        assignedTo: "Mohamed Sami",
    },
    {
        id: "1233",
        title: "Grand House Real Estate",
        location: "New Cairo, Egypt",
        price: 7500000,
        rooms: 3,
        bathrooms: 3,
        area: 250,
        image: "/unit_3.png",
        status: "approved",
        reserved: true,
        addedDate: "15/8/2022",
        assignedTo: "Mohamed Sami",
    },
    {
        id: "1234",
        title: "Grand House Real Estate",
        location: "New Cairo, Egypt",
        price: 23500000,
        rooms: 3,
        bathrooms: 3,
        area: 250,
        image: "/unit_4.png",
        status: "rejected",
        addedDate: "31/8/2022",
    },
    {
        id: "153",
        title: "Grand House Real Estate",
        location: "New Cairo, Egypt",
        price: 13500000,
        rooms: 3,
        bathrooms: 3,
        area: 250,
        image: "/unit_3.png",
        status: "approved",
        reserved: true,
        addedDate: "31/8/2022",
        assignedTo: "Mohamed Sami",
    },
    {
        id: "1034",
        title: "Grand House Real Estate",
        location: "New Cairo, Egypt",
        price: 13500000,
        rooms: 3,
        bathrooms: 3,
        area: 250,
        image: "/unit_4.png",
        status: "rejected",
        addedDate: "31/8/2022",
    },
];
